spring.application.name=VelocityFlow
spring.datasource.url= jdbc:postgresql://localhost:5432/velocityflow

spring.datasource.username= postgres

spring.datasource.password= root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=9090

app.jwt.secret="fsdkjfklsdjflksdjfklsjdlfjsdl;fjsdl;kfjsd;lkfj;klsfj;klsfsdffsdkjfklsdjflksdjfklsjdlfjsdl;fjsdl;kfjsd;lkfj;klsfj;klsfsdffsdkjfklsdjflksdjfklsjdlfjsdl;fjsdl;kfjsd;lkfj;klsfj;klsfsdf"

app.jwt.expiration-in-ms= 10000


request.origin.url= http://localhost:9090/
